.PHONY: clean All

All:
	@echo "----------Building project:[ test_cpp - Debug ]----------"
	@cd "test_cpp" && $(MAKE) -f  "test_cpp.mk"
clean:
	@echo "----------Cleaning project:[ test_cpp - Debug ]----------"
	@cd "test_cpp" && $(MAKE) -f  "test_cpp.mk" clean
